### ISSUE TITLE
Maybe a typo in `SPM tools` hyperlink in README?

### ISSUE THREAD

**Issue by riteshhgupta** [AckeeCZ/tapestry#7]
Hi, I just noticed that in the README there might a typo in SPM tool hyperlink since currently it also points to Tuist? Maybe the link is different for SPM tools? Though I'm not 💯 sure hence maybe :)

**Comment by fortmarek** [comment]
Oh my, you are absolutely right, I will push a fix right away 🤦‍♂ Thanks for the report!
